name: jira

on:
  workflow_dispatch:

concurrency: this

env:
  JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

jobs:
  jira:
    needs: [ testjob ]
    if: failure() and github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: jira-notification-action
        uses: champ-oss/action-jira-notification@v1.0.0
        with:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_HOST: ${{ secrets.JIRA_HOST }}
          JIRA_PROJECT: TEST
          JIRA_USER: ${{ secrets.JIRA_USER }}
          GITHUB_WORKFLOW_NAME: ${{ env.GITHUB_WORKFLOW_NAME }}
          JIRA_TYPE: Problem
  testjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: exit 1

