name: jira

on:
  workflow_dispatch:

concurrency: this

env:
  JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

jobs:
  jira:
    needs: [ test-job ]
    if: failure() || success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set env var
        run: |
          if [[ ${{ needs.test-job.result }} == success ]]; then
             echo "GITHUB_JOB_STATUS=success" >> $GITHUB_ENV
          else
             echo "GITHUB_JOB_STATUS=failure" >> $GITHUB_ENV
          fi
      - name: jira-notification-action
        uses: champ-oss/action-jira-notification@main
        with:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_HOST: ${{ secrets.JIRA_HOST }}
          JIRA_PROJECT: TEST
          JIRA_USER: ${{ secrets.JIRA_USER }}
          GITHUB_WORKFLOW_NAME: ${{ env.GITHUB_WORKFLOW_NAME }}
          JIRA_TYPE: Problem
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: exit 1

