name: update
description: https://github.com/champ-oss/action-jira-notication
inputs:
  JIRA_PROJECT:
    description: 'jira project to open ticket'
    required: true
    default: 'CTEST'
  JIRA_TOKEN:
    description: 'token used to auth with jira'
    required: true
  JIRA_USER:
    description: 'user used to auth with jira'
    required: true
  JIRA_HOST:
    description: 'jira host'
    required: true
  JIRA_TYPE:
    description: 'jira type'
    required: true
    default: 'Incident'
runs:
  using: "composite"
  steps:
    - name: install jira lib
      shell: bash
      run: cd ${{github.action_path}} && pip3 install -r requirements.txt
    - name: run python script
      shell: bash
      env:
        JIRA_PROJECT: ${{ inputs.JIRA_PROJECT }}
        JIRA_TOKEN: ${{ inputs.JIRA_TOKEN }}
        JIRA_USER: ${{ inputs.JIRA_USER }}
        JIRA_HOST: ${{ inputs.JIRA_HOST }}
        JIRA_TYPE: ${{ inputs.JIRA_TYPE }}
      run: |
        python ${GITHUB_ACTION_PATH}/action-jira-notification.py
